### ISSUE TITLE
while adding a playlist it says added play list of songs to queue and connection initiates but the song doesnt play and queue seems empty

### ISSUE THREAD

**Issue by pratheek157qwds** [riffy-team/riffy-music-bot#7]
![image](https://github.com/user-attachments/assets/aa97439f-089a-4e20-86bf-d93035df5ae6)

**Comment by UnschooledGamer** [comment]
> ![image](https://private-user-images.githubusercontent.com/154472124/371240498-aa97439f-089a-4e20-86bf-d93035df5ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzAzNjgsIm5iZiI6MTcyNzM3MDA2OCwicGF0aCI6Ii8xNTQ0NzIxMjQvMzcxMjQwNDk4LWFhOTc0MzlmLTA4OWEtNGUyMC04NmJmLWQ5MzAzNWRmNWFlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNzAxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODI4MDE3YjlmNTRkNDIwZGEzOGVlMWU4NGE0NjZmN2M5ZmIwNDY2NDUzYmY0ZTZlOTA0MmVmOGVhMWQyMjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rkYPlrCV9rF-DJBUq4fn9gzWWMAzDPrCOZD35Eq5viU)

1. I would like you have a view of your queue.
2. And Logs of Lavalink (if you have access to those)
3. Lastly, Your Play Command

**Comment by pratheek157qwds** [comment]
1.
![image](https://github.com/user-attachments/assets/b039f0b8-5582-46fd-8a02-b7118b7ade86)
2. i dont have access to lavalink because i use a public lavalink
3.case 'play': {
    			const playlistName = interaction.options.getString('playlist_name');
    			const playlists = await db.get(playlistsKey) || {};

    		if (!playlists[playlistName]) {
        		return interaction.reply({ content: 'This playlist does not exist.', ephemeral: true });
    		}

    		const songs = playlists[playlistName];
    		if (!songs.length) {
        		return interaction.reply({ content: 'The playlist is empty.', ephemeral: true });
    		}

    		await interaction.deferReply();//reply instantly to fix bot not is responding

    		const player = client.riffy.createConnection({
        		guildId: interaction.guild.id,
        		voiceChannel: interaction.member.voice.channel.id,
        		textChannel: interaction.channel.id,
        		deaf: true,
    		});

    		let addedSongs = 0;
    		for (const song of songs) {
        		try {
            		const resolve = await client.riffy.resolve({ query: song, requester: interaction.member });
            		const { loadType, tracks } = resolve;

            		if (loadType === 'track' || loadType === 'search') {
                		const track = tracks[0];
                		track.info.requester = interaction.member;
                		player.queue.add(track);
                		addedSongs++;
            		}
        		} catch (error) {
            		console.error(`Failed to resolve or add song: ${song}`, error);
            		continue;
        		}
    		}

    		const playlistEmbed = new EmbedBuilder()
        		.setColor('#2f3136')
        		.setTitle('Playlist Added')
        		.setDescription(`Added **${addedSongs}** songs from playlist **${playlistName}** to the queue.`)
        		.setTimestamp();

    		await interaction.editReply({ embeds: [playlistEmbed] });

    		if (!player.playing && !player.paused && player.queue.totalSize) {
        		player.play();
    		}

    		break;
            }
        }
    },
};

**Comment by UnschooledGamer** [comment]
> ![image](https://private-user-images.githubusercontent.com/154472124/371458948-b039f0b8-5582-46fd-8a02-b7118b7ade86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Mjg5ODUsIm5iZiI6MTcyNzQyODY4NSwicGF0aCI6Ii8xNTQ0NzIxMjQvMzcxNDU4OTQ4LWIwMzlmMGI4LTU1ODItNDZmZC04YTAyLWI3MTE4YjdhZGU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwOTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWY4NjcxYjA5ODg5ODI5MjM0ZGJmMjg1MmQ2MWZkODVlNTY3ZTliMjgzMDY1N2MzZTI1Mjk2Y2YxMmZiYmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y-hOCYEc74F0WFa1FJpe_65bAR0Wwln-nwW3flDDnXk) 2. i dont have access to lavalink because i use a public lavalink 3.case 'play': { const playlistName = interaction.options.getString('playlist_name'); const playlists = await db.get(playlistsKey) || {};
> 
> ```
> 		if (!playlists[playlistName]) {
>     		return interaction.reply({ content: 'This playlist does not exist.', ephemeral: true });
> 		}
> 
> 		const songs = playlists[playlistName];
> 		if (!songs.length) {
>     		return interaction.reply({ content: 'The playlist is empty.', ephemeral: true });
> 		}
> 
> 		await interaction.deferReply();//reply instantly to fix bot not is responding
> 
> 		const player = client.riffy.createConnection({
>     		guildId: interaction.guild.id,
>     		voiceChannel: interaction.member.voice.channel.id,
>     		textChannel: interaction.channel.id,
>     		deaf: true,
> 		});
> 
> 		let addedSongs = 0;
> 		for (const song of songs) {
>     		try {
>         		const resolve = await client.riffy.resolve({ query: song, requester: interaction.member });
>         		const { loadType, tracks } = resolve;
> 
>         		if (loadType === 'track' || loadType === 'search') {
>             		const track = tracks[0];
>             		track.info.requester = interaction.member;
>             		player.queue.add(track);
>             		addedSongs++;
>         		}
>     		} catch (error) {
>         		console.error(`Failed to resolve or add song: ${song}`, error);
>         		continue;
>     		}
> 		}
> 
> 		const playlistEmbed = new EmbedBuilder()
>     		.setColor('#2f3136')
>     		.setTitle('Playlist Added')
>     		.setDescription(`Added **${addedSongs}** songs from playlist **${playlistName}** to the queue.`)
>     		.setTimestamp();
> 
> 		await interaction.editReply({ embeds: [playlistEmbed] });
> 
> 		if (!player.playing && !player.paused && player.queue.totalSize) {
>     		player.play();
> 		}
> 
> 		break;
>         }
>     }
> },
> ```
> 
> };

What's `queue.totalSize`? As it doesn't exist in Riffy

**Comment by pratheek157qwds** [comment]
it checks if the queue has atleast 1 song in it. player.queue.size

**Comment by pratheek157qwds** [comment]
thankyou done i used play.queue.totalsize and now it is fixed.
